[package]
name = "sui-capybaras"
version = "0.1.0"

[dependencies]
[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.19.0
rev = "2d709054a08d904b9229a2472af679f210af3827"
# ObjectID: 0xa40626b974304ef92d2210e71a55691b9ca1e171

[addresses]
capy = "0"
